name = "EnergySystemModel"
uuid = "2f1a2cda-0a35-11ea-0485-13adf048beb5"
authors = ["Jaan Tollander de Balsch <jaan.tollander@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
